steps:
  - name: "node:18-alpine"
    entrypoint: yarn

  - name: "node:18-alpine"
    entrypoint: "yarn"
    args: ["create-env"]
    env:
      - DATABASE_URL${_DATABASE_URL}
      - MYSQL_DB_USERNAME${_MYSQL_DB_USERNAME}
      - MYSQL_DB_PASSWORD${_MYSQL_DB_PASSWORD}
      - NEXTAUTH_SECRET${_NEXTAUTH_SECRET}
      - NEXTAUTH_URL${_NEXTAUTH_URL}
      - DISCORD_CLIENT_ID${_DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET${_DISCORD_CLIENT_SECRET}
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY${_NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY${_CLERK_SECRET_KEY}
      - OPENAI_API_KEY${_OPENAI_API_KEY}

  - name: "node:18-alpine"
    entrypoint: yarn
    args: ["build"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"
