steps:
  - name: $_NODE_VERSION
    entrypoint: yarn
    args: ["install", "build"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NODE_VERSION: node:14.5.0-alpine # default value

images:
  - "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"
