steps:
  - name: "node:18-alpine"
    entrypoint: yarn

  - name: "node:18-alpine"
      - 'run'
      - 'bash'
      - '-c'
      - |
        echo "DATABASE_URL='$$DATABASE_URL'" > .env
        echo "MYSQL_DB_USERNAME='$$MYSQL_DB_USERNAME'" >> .env
        echo "MYSQL_DB_PASSWORD='$$MYSQL_DB_PASSWORD'" >> .env
        echo "NEXTAUTH_SECRET='$$NEXTAUTH_SECRET'" >> .env
        echo "NEXTAUTH_URL='$$NEXTAUTH_URL'" >> .env
        echo "DISCORD_CLIENT_ID='$$DISCORD_CLIENT_ID'" >> .env
        echo "DISCORD_CLIENT_SECRET='$$DISCORD_CLIENT_SECRET'" >> .env
        echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY='$$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY'" >> .env
        echo "CLERK_SECRET_KEY='$$CLERK_SECRET_KEY'" >> .env
        echo "OPENAI_API_KEY='$$OPENAI_API_KEY'" >> .env

      - '&&'
      - 'yarn'
      - 'build'

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"
