steps:
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]

  - name: "gcr.io/cloud-builders/yarn"
    args: ["build"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"]

images:
  - "gcr.io/$PROJECT_ID/knock-knock:$COMMIT_SHA"
